"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const dotenv_1 = __importDefault(require("dotenv"));
const http_1 = require("http");
const user_route_1 = __importDefault(require("./user/user.route"));
const auth_route_1 = __importDefault(require("./auth/auth.route"));
const teacher_route_1 = __importDefault(require("./teacher/teacher.route"));
const student_route_1 = __importDefault(require("./student/student.route"));
const course_route_1 = __importDefault(require("./course/course.route"));
const cors_1 = __importDefault(require("cors"));
const teacherQualification_route_1 = __importDefault(require("./teacherQualification/teacherQualification.route"));
const courseTopic_route_1 = __importDefault(require("./courseTopic/courseTopic.route"));
const section_route_1 = __importDefault(require("./section/section.route"));
const quiz_route_1 = __importDefault(require("./quiz/quiz.route"));
const question_route_1 = __importDefault(require("./question/question.route"));
const option_route_1 = __importDefault(require("./option/option.route"));
const roadMap_route_1 = __importDefault(require("./roadMap/roadMap.route"));
const requireCourse_route_1 = __importDefault(require("./requireCourse/requireCourse.route"));
const certification_route_1 = __importDefault(require("./certification/certification.route"));
const join_route_1 = __importDefault(require("./join/join.route"));
const dO_route_1 = __importDefault(require("./dO/dO.route"));
const answerRecord_route_1 = __importDefault(require("./answerRecord/answerRecord.route"));
const lecture_route_1 = __importDefault(require("./lecture/lecture.route"));
const interact_route_1 = __importDefault(require("./interact/interact.route"));
const includeCourse_route_1 = __importDefault(require("./includeCourse/includeCourse.route"));
const viewRoadMap_route_1 = __importDefault(require("./viewRoadMap/viewRoadMap.route"));
dotenv_1.default.config();
const app = (0, express_1.default)();
const port = process.env.PORT || 4000;
app.use((0, cors_1.default)()); // Enable CORS
app.use(express_1.default.json());
app.use('/user', user_route_1.default);
app.use('/student', student_route_1.default);
app.use('/teacher', teacher_route_1.default);
app.use('/auth', auth_route_1.default);
app.use('/course', course_route_1.default);
app.use('/teacherQualification', teacherQualification_route_1.default);
app.use('/courseTopic', courseTopic_route_1.default);
app.use('/section', section_route_1.default);
app.use('/quiz', quiz_route_1.default);
app.use('/question', question_route_1.default);
app.use('/option', option_route_1.default);
app.use('/roadMap', roadMap_route_1.default);
app.use('/requireCourse', requireCourse_route_1.default);
app.use('/certification', certification_route_1.default);
app.use('/join', join_route_1.default);
app.use('/dO', dO_route_1.default);
app.use('/answerRecord', answerRecord_route_1.default);
app.use('/lecture', lecture_route_1.default);
app.use('/interact', interact_route_1.default);
app.use('/includeCourse', includeCourse_route_1.default);
app.use('/viewRoadMap', viewRoadMap_route_1.default);
const server = (0, http_1.createServer)(app);
server.listen(port, () => {
    console.log(`[server]: Server is running at http://localhost:${port}`);
});
